"PROG" = "Positions Pipeline"
"DESCRIPTION" = "This pipeline builds a dataset of information about the diversity and functions of positions in MHC molecules."
"EPILOG" = "For more information see - https = //github.com/histofyi/positions_pipeline"

[ARGUMENTS.VERBOSE]
"FLAG" = "v"
"VARIABLE_NAME" = "verbose"
"HELP" = "increases output verbosity (non-verbosity is the default)"
"ACTION" = "store_true"
"DEFAULT" = false

[ARGUMENTS.FORCE]
"FLAG" = "f"
"VARIABLE_NAME" = "force"
"HELP" = "forces reloading of underlying datasets (not forcing reload is the default)"
"ACTION" = "store_true"
"DEFAULT" = false

[ARGUMENTS.RELEASE]
"FLAG" = "r"
"VARIABLE_NAME" = "release"
"HELP" = "switch between development and release modes (development mode is the default)"
"ACTION" = "store_true"
"DEFAULT" = false